### PR TITLE
Problem: main development branch is obscurely named

### PR DESCRIPTION
**Pull request by yrashk**
poa-dev-2 is not the most obvious place to look for.

Proposed solution: merge it into master.

### CODE REVIEW

**Comment by igorbarinov** [comment]
Good idea to keep master in master. Should we remove forked repo and recreate it without the link to upstream?

**Comment by yrashk** [comment]
That's rather a cosmetical decision to make. Either is fine.

**Comment by rstormsf** [comment]
👍

**Comment by yrashk** [comment]
Any objections to this one?

**Comment by rstormsf** [comment]
@yrashk zero

**Comment by akolotov** [comment]
@yrashk I am waiting for response from @igorbarinov

**Comment by yrashk** [comment]
It is an entirely reversible decision, actually.

**Comment by akolotov** [comment]
I understand this. There is no rush with switching the branch - I do not see how it blocks resolving of any other issues we have.

**Comment by yrashk** [comment]
It only blocks in a sense that if I will be sending pull requests to poa-dev-2 for now I'd need to update this PR, too. to include those, post-merge.

**Comment by akolotov** [comment]
That's why my suggestion is to discuss such kind of proposal before doing actual PR. I like a process when we open an issue, discuss it and implement changes as per discussion.

**Comment by akolotov** [comment]
Discussed the branch swapping with Igor. We will switch our main branch to `master`.

**Pull request merged**
